# 支持YOLO模型的配置文件
# 结合训练好的弹出框检测模型 + Tesseract OCR + BERT语义分析

chat_app:
  name: "Mango"
  # 【常规】 客户端项目-pic: xx24.jpeg
  # target_contacts: ["js_wbmalia-研发部助理", "人事小姐姐"]
  target_contacts:
    - js_wbmalia-研发部助理
    - 人事小姐姐
  fuzzy_match:
    enabled: true
    similarity_threshold: 0.5  # 50%相似度阈值
    min_length: 2  # 最小匹配长度

monitor:
  check_interval: 1
  reply_wait: 3
  # 应用监控开关
  process_monitor_on: true
  # 网络监控开关
  network_monitor_on: true
  # 声音提醒开关
  sound_alert_on: true
  # 自动回复开关
  auto_reply_on: false

# YOLO模型配置
yolo:
  enabled: true
  model_path: "models/best.pt"  # 使用训练好的模型
  confidence: 0.6 # 检测置信度阈值（降低以提高检测率）
  use_fallback: true  # 如果YOLO失败，使用全屏OCR备用方案

ocr:
  tesseract:
    lang: "chi_sim+eng"
    config: "--psm 6"
    use_preprocessing: true
  text_correction:
    enabled: true
    char_corrections:
      "儆": "警"
      "千": "干"
      "千": "于"
      "儆": "惊"
      "0": "O"
      "1": "l"
      "5": "S"
      "8": "B"
    phrase_corrections:
      "回复1": "回复1"
      "发送照片": "发送照片"
      "收到": "收到"
      "好的": "好的"
      "谢谢": "谢谢"
      "再见": "再见"

semantic:
  model_name: "hfl/chinese-bert-wwm-ext"
  enabled: true
  confidence_threshold: 0.65

preprocessing:
  clahe:
    clip_limit: 2.0
    tile_grid_size: [8, 8]
  denoising:
    enabled: true
    method: "fastNlMeansDenoising"
  threshold:
    method: "OTSU"
  morphology:
    enabled: true
    operation: "CLOSE"
    kernel_size: [1, 1]

debug:
  save_processed_images: false
  save_detection_images: true  # 保存YOLO检测到的弹出框图像
  verbose: true

# 网络监控配置
network_monitor:
  enabled: true
  check_interval: 10          # 检测间隔（秒）
  timeout: 5                  # 超时时间（秒）
  consecutive_failures: 3     # 连续失败次数阈值
  tolerance_minutes: 0.1      # 容错时间（分钟）
  # check_interval: 60          # 检测间隔（秒）
  # timeout: 10                 # 超时时间（秒）
  # consecutive_failures: 6     # 连续失败次数阈值
  # tolerance_minutes: 0.5       # 容错时间（分钟）
  test_targets:              # 检测目标
    - name: "谷歌"
      url: "https://www.google.com"
      method: "http"
    - name: "GitHub"
      url: "https://github.com"
      method: "http"

# 明确包含的功能
included_features:
  - "yolo_detection"  # YOLO弹出框检测
  - "tesseract_ocr"   # Tesseract OCR
  - "bert_semantic"   # BERT语义分析
  - "network_monitor" # 网络监控
  - "process_monitor" # 进程监控 