chat_app:
  name: Mango
  target_contacts:
  - js_wbmalia-研发部助理
  - 客户端项目
  fuzzy_match:
    enabled: true
    similarity_threshold: 0.5
    min_length: 2
monitor:
  check_interval: 1.0
  reply_wait: 3.0
yolo:
  enabled: true
  model_path: models/best.pt
  confidence: 0.8
  use_fallback: true
ocr:
  tesseract:
    lang: chi_sim+eng
    config: --psm 6
    use_preprocessing: true
  text_correction:
    enabled: true
    char_corrections:
      儆: 惊
      千: 于
      '0': O
      '1': l
      '5': S
      '8': B
    phrase_corrections:
      回复1: 回复1
      发送照片: 发送照片
      收到: 收到
      好的: 好的
      谢谢: 谢谢
      再见: 再见
semantic:
  model_name: hfl/chinese-bert-wwm-ext
  enabled: true
  confidence_threshold: 0.65
preprocessing:
  clahe:
    clip_limit: 2.0
    tile_grid_size:
    - 8
    - 8
  denoising:
    enabled: true
    method: fastNlMeansDenoising
  threshold:
    method: OTSU
  morphology:
    enabled: true
    operation: CLOSE
    kernel_size:
    - 1
    - 1
debug:
  save_processed_images: false
  save_detection_images: true
  verbose: true
network_monitor:
  enabled: true
  check_interval: 3.0
  timeout: 5.0
  consecutive_failures: 2
  tolerance_minutes: 0.1
  test_targets:
  - name: 谷歌
    url: https://www.google.com
    method: http
  - name: GitHub
    url: https://github.com
    method: http
included_features:
- yolo_detection
- tesseract_ocr
- bert_semantic
- network_monitor
- process_monitor
popup_settings:
  fast_mode: false
